# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/smartai',
                'doc_host': 'https://CausalTruth.github.io',
                'git_url': 'https://github.com/CausalTruth/smartai',
                'lib_path': 'smartai'},
  'syms': {'smartai.core': {'smartai.core.foo': ('core.html#foo', 'smartai/core.py')}}}
